### ISSUE TITLE
bug: variables and variables_files ignore from .venomrc

### ISSUE THREAD

**Issue by YoannAtOVH** [Thiht/vscode-venom#3]
Hello,

If I declare some variables_files in .venomrc like:
```
variables_files:
  - ovh_api.yaml
```
there are not take in account during Run Test

Error message:
`unknown endpoint '', consider checking 'Endpoints' list of using an URL`

If I declare on top of test file:
```
vars:
  ovh.endpoint: 'ovh-eu'
```

Error message change to:
`missing application key, please check your configuration or consult the documentation to create one`

Content of ovh_api.yaml:
```
ovh.endpoint: 'ovh-eu'
ovh.applicationKey: xxxx
ovh.applicationSecret: xxxx
ovh.consumerKey: xxxx
```

If I run venom from shell, no error.

Same if I set variable directly:
```
variables: 
  - ovh.endpoint='ovh-eu'
  - ovh.applicationKey=xxxx
  - ovh.applicationSecret=xxxx
  - ovh.consumerKey=xxxx
```

Regards,

**Comment by Thiht** [comment]
Hi,
The .venomrc is loaded by Venom directly from the current working directory, which is set as the root of your open project.

You can check Venom's CWD like this: run a test -> click the "Show output button" at the top -> check the "Working directory: xxx" line in the terminal

https://user-images.githubusercontent.com/2796344/188511555-7ebf6d04-3401-4566-9883-53bcc7c1c993.mov

Can you check if your .venomrc is in this location?

**Comment by YoannAtOVH** [comment]
Hello,

In fact, VSCode offer me to run test at different levels:
![](https://dl.plik.ovh/file/7IPZxOSe5NKmOY7Z/1FH6aPzUKx3gpJbY/OpenVSCode.png)

It can be
1. at the venom.yml file
2. at the folder level
3. at a parent folder level

So I made a (wrong) assumption that the extension chdir to the directory from where the user click to run the test suite.
